---
- hosts: all
  sudo: yes
  vars:
    vagrant_ip: 192.168.10.05
    mysql_root_password: password

  tasks:
  - name: install htop
    apt: name=htop state=present

  - name: Install MySQL
    sudo: yes
    apt: name={{ item }} state=installed
    with_items:
      - mysql-server-5.6
      - mysql-client-5.6
      - libmysqlclient-dev
      - python-mysqldb
        
  - name: Create database
    mysql_db: db=phase23 state=present
    
  - name: Install user
    mysql_user: name=helianto host=% password=helianto priv=phase23.*:ALL,GRANT state=present
      
  - name: Ensure MySQL will listen on all ip interfaces (bind to 0.0.0.0)
    lineinfile: dest=/etc/mysql/my.cnf
      regexp='bind-address\s*=\s*127\.0\.0\.1\s*'
      line='bind-address   = 0.0.0.0'
      state=present
      backrefs=yes
    notify: restart mysql
  